### ISSUE TITLE
git clone (checkout) on windows fails with "unable to create file LectureNotes/Math227c/Icon?: Invalid argument"

### ISSUE THREAD

**Issue by pderdeyn** [allardjun/Math227C#1]
**Reproduce**: by running `git clone https://github.com/allardjun/Math227C.git` on windows

**Expected**: Repository is in my filesystem and I can do git commands with it

**Actual**: Command fails with the following error:
error: unable to create file LectureNotes/Math227c/Icon?: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

The issue seems to be that this file doesn't have an extension, which is ok on Mac, but on Windows it is marked with "?" as an extension and then fails

**Fix**: I'm not sure where this file is used so I can't really recommend how to fix. Either remove it or make it a png or jpg?

**Workaround**: It seems there are some git gui's like the github windows app that can magically handle it

**Comment by allardjun** [comment]
The file is automatically created by the iPad note-taking app (Notability). I've removed it from the sync.

**Comment by pderdeyn** [comment]
Thanks! Works fine for me now :D
